version: "3"

services:
  node:
    build: .
    container_name: swift-send-app
    command: bash
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
      - 5555:5555
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      JWT_SECRET: secretJWT
      API_HOST: 'node'
      PORT: 3000
      NODE_ENV: 'development'
    networks:
      - swift-send-net

  db:
    container_name: swift-send-db
    image: mysql:8.0.23
    # platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - swift-send-net

networks:
  swift-send-net:
    driver: bridge

